### ISSUE TITLE
Exporting data from website to xls

### ISSUE THREAD

**Issue by ThomasMGeo** [StraboSpot/strabo-spot#2]
Hello, how can I get the elevation to export as well?

**Comment by jasonash** [comment]
Thomas, we will add elevation to the xls export.

**Comment by jasonash** [comment]
Thomas,

Altitude (elevation) has been added to the XLS export. I hope this helps. Please let us know if you need anything else.

**Comment by ThomasMGeo** [comment]
Hi Jason, really appreciate it!

For the future, you might call the column altitude_m or Altitude(m) so people know it's meters. I really appreciate the quick turn around.

**Comment by jasonash** [comment]
OK, I switched it to Altitude(m) per your suggestion.

Thanks,

Jason

**Comment by jasonash** [comment]
OK to close.
