### ISSUE TITLE
Exporting as UTM's?

### ISSUE THREAD

**Issue by ThomasMGeo** [StraboSpot/strabo-spot#3]
Hello,

Thanks again for all of the help. I was wondering how hard it would be to be able to export in UTM's with lat and longs for the xls?

I really like being a strabo user! 

Thanks again,
Thomas

**Comment by jasonash** [comment]
Thomas,
Unfortunately, we are unable to export locations in UTM. StraboSpot is not meant to be a replacement for GIS, and does not have robust GIS functionality.

**Comment by jasonash** [comment]
OK to close.
